version: 0.2
phases:
  pre_build:
    commands:
      - echo checking code quality...
      - npm install
  build:
    commands:
      - echo creating build...
			- npm start
  post_build:
    commands:
      - echo POST BUILD...
