version: 0.2
phases:
  pre_build:
    commands:
      - echo checking code quality...
      - npm install --verbose
  build:
    commands:
      - echo creating builddd...
      - npm run build
  post_build:
    publicKey: '{{resolve:secretsmanager:poc_password_key_pair:SecretString:public_key}}'
    commands:
      # copy the contents of /build to S3 bucket
      - aws s3 sync build s3://$DEPLOYMENT_BUCKET/ --delete --exclude 'index.html' --acl public-read --cache-control 'max-age=860000'
      - aws s3 sync build s3://$DEPLOYMENT_BUCKET/ --delete --exclude '*' --include 'index.html' --acl public-read --cache-control 'max-age=0'
      
